### ISSUE TITLE
CSRF will fail if AJAX is on site

### ISSUE THREAD

**Issue by CorvinSteindl** [adbario/slim-csrf#3]
It says Wrong key (If you do the POST Request) if on the same site where ajax loaded before

**Comment by adbario** [comment]
If you use ajax, you also need to update the token in your form hidden field, as every request has a new csrf token. When you use ajax with form, the page is not reloaded automatically so you need to update csrf token i.e. with json response.

**Comment by CorvinSteindl** [comment]
Okay could you give me an example?

**Comment by adbario** [comment]
You're already reading json response, otherwise you wouldn't know if the form submission is failed or not etc. So you can add freshly generated CSRF token to your response and at frontend JS you will replace old token with the new one, then you're ready to make a new request with valid token. Optionally you can return fresh token with http headers too or with cookies. Frontend you will have to code by yourself, it has nothing to do with Slim or this script itself.

At some point I will add more functionality to this script, that will also help with your case, but not sure about the schedule yet.
